<a href="https://colab.research.google.com/github/Shubhayang6/Numpy-basics/blob/main/arrays%20and%20matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
my_list=list(range(10))


In [5]:
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
array_1=np.array(my_list)

In [8]:
print(array_1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
multi_list=[[1,2,3,4,5,6],[7,8,9,10,11,12]]
array_2=np.array(multi_list)
print(multi_list)

In [11]:
print(array_2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [16]:
array_1.ndim

1

In [15]:
array_2.ndim

2

In [18]:
array_2.shape

(2, 6)

In [19]:
multi_2x3=[[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]

In [21]:
array_multi_2x3=np.array(multi_2x3)
print(array_multi_2x3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [23]:
array_multi_2x3.ndim

3

In [24]:
array_multi_2x3.shape

(3, 2, 2)

In [26]:
multi_3x3=[[[1,2,0],[3,4,0]],[[5,6,0],[7,8,0]],[[9,10,0],[11,12,0]]]
print(multi_3x3)

[[[1, 2, 0], [3, 4, 0]], [[5, 6, 0], [7, 8, 0]], [[9, 10, 0], [11, 12, 0]]]


In [28]:
array_multi_3x3=np.array(multi_3x3)
print(array_multi_3x3)

[[[ 1  2  0]
  [ 3  4  0]]

 [[ 5  6  0]
  [ 7  8  0]]

 [[ 9 10  0]
  [11 12  0]]]


In [29]:
print(array_multi_3x3.ndim)
print(array_multi_3x3.shape)

3
(3, 2, 3)


In [30]:
print(array_2.dtype)

int64


In [31]:
print(array_1.dtype )

int64


In [34]:
my_list2=[1,2,3,4,5,6.5,7,8,9]

In [37]:
array_3=np.array(my_list2)
print(array_3)

[1.  2.  3.  4.  5.  6.5 7.  8.  9. ]


In [39]:
print(array_3.dtype)

float64


In [45]:
zeros_array=np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [46]:
zeros_ndarray=np.zeros((3,6))
print(zeros_ndarray)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [48]:
ones_array=np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [53]:
empty_array=np.empty((3,3,2))
print(empty_array)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [55]:
array_arange=np.arange(20)
print(array_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [57]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [58]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [59]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])