<a href="https://colab.research.google.com/github/Shubhayang6/Numpy-basics/blob/main/boolean%20indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
days=np.array(['sun','mon','tue','wed','thur','fri','sat','sun','thur','thur'])

In [5]:
data=np.random.randn(10,4)
data

array([[-0.82412956, -1.86959831, -1.15171079, -1.08628687],
       [ 0.35679507, -0.39134766,  1.3091819 ,  0.34822747],
       [-0.05642771,  0.89147817,  1.11191778,  0.39854997],
       [ 0.3428245 ,  0.56111248, -1.11823879, -0.29554765],
       [ 1.11079811,  1.03362859, -0.13879541, -1.29944136],
       [ 0.89071004, -0.36260303,  1.03671779, -1.92044084],
       [ 0.18199059, -0.04115906, -0.76029977, -0.35297352],
       [-0.24463305,  1.28276949,  1.20279142, -1.30746863],
       [ 0.38422922,  1.34980627, -2.01508922, -0.63464121],
       [ 0.361287  ,  0.17892449,  0.97647995,  1.28324545]])

In [6]:
days=='sun'

array([ True, False, False, False, False, False, False,  True, False,
       False])

In [7]:
data[days=='sun']

array([[-0.82412956, -1.86959831, -1.15171079, -1.08628687],
       [-0.24463305,  1.28276949,  1.20279142, -1.30746863]])

In [8]:
data[days=='sun',1:]

array([[-1.86959831, -1.15171079, -1.08628687],
       [ 1.28276949,  1.20279142, -1.30746863]])

In [9]:
days!='sun'

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True])

In [10]:
data[days!='sun']

array([[ 0.35679507, -0.39134766,  1.3091819 ,  0.34822747],
       [-0.05642771,  0.89147817,  1.11191778,  0.39854997],
       [ 0.3428245 ,  0.56111248, -1.11823879, -0.29554765],
       [ 1.11079811,  1.03362859, -0.13879541, -1.29944136],
       [ 0.89071004, -0.36260303,  1.03671779, -1.92044084],
       [ 0.18199059, -0.04115906, -0.76029977, -0.35297352],
       [ 0.38422922,  1.34980627, -2.01508922, -0.63464121],
       [ 0.361287  ,  0.17892449,  0.97647995,  1.28324545]])

In [12]:
cond=(days=='sun')
cond

array([ True, False, False, False, False, False, False,  True, False,
       False])

In [14]:
multi_cond=(days=='sun')|(days=='thur')
multi_cond

array([ True, False, False, False,  True, False, False,  True,  True,
        True])

In [15]:
data[multi_cond]

array([[-0.82412956, -1.86959831, -1.15171079, -1.08628687],
       [ 1.11079811,  1.03362859, -0.13879541, -1.29944136],
       [-0.24463305,  1.28276949,  1.20279142, -1.30746863],
       [ 0.38422922,  1.34980627, -2.01508922, -0.63464121],
       [ 0.361287  ,  0.17892449,  0.97647995,  1.28324545]])

In [17]:
data[data<0]=0
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.35679507, 0.        , 1.3091819 , 0.34822747],
       [0.        , 0.89147817, 1.11191778, 0.39854997],
       [0.3428245 , 0.56111248, 0.        , 0.        ],
       [1.11079811, 1.03362859, 0.        , 0.        ],
       [0.89071004, 0.        , 1.03671779, 0.        ],
       [0.18199059, 0.        , 0.        , 0.        ],
       [0.        , 1.28276949, 1.20279142, 0.        ],
       [0.38422922, 1.34980627, 0.        , 0.        ],
       [0.361287  , 0.17892449, 0.97647995, 1.28324545]])

In [18]:
data[days!='sun']=0.5
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.        , 1.28276949, 1.20279142, 0.        ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ]])