<a href="https://colab.research.google.com/github/Shubhayang6/Numpy-basics/blob/main/conditional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
datax=np.array(np.arange(5))
datax

array([0, 1, 2, 3, 4])

In [4]:
datay=np.array(np.arange(5,10))
datay

array([5, 6, 7, 8, 9])

In [7]:
cond=np.array([True,False,False,True,True])

In [9]:
result_where=np.where(cond,datax,datay)
result_where

array([0, 6, 7, 3, 4])

In [10]:
dataz=np.random.randn(10,4)
dataz

array([[-0.88341077, -0.31692026, -0.20435859,  0.01483979],
       [ 0.32123303,  0.47667477, -0.6709953 , -2.8732523 ],
       [ 1.26586057, -1.26263506,  0.05063025,  1.23980119],
       [-1.59270947,  0.67381778,  0.16615987, -2.0839829 ],
       [-0.38393477,  3.27111243,  1.97494344,  0.43814239],
       [ 0.35297972,  1.15771007, -0.06159884, -1.15060275],
       [ 1.09660142, -0.43272997,  0.37519373,  0.25487798],
       [-0.1520418 ,  0.93791874,  0.06059655,  0.137776  ],
       [ 1.65983811,  0.58595194,  1.30090325,  1.5147392 ],
       [-0.72744689,  0.13538309,  1.05059679,  1.76535473]])

In [14]:
result2=np.where(dataz>0,5,-5)
result2

array([[-5, -5, -5,  5],
       [ 5,  5, -5, -5],
       [ 5, -5,  5,  5],
       [-5,  5,  5, -5],
       [-5,  5,  5,  5],
       [ 5,  5, -5, -5],
       [ 5, -5,  5,  5],
       [-5,  5,  5,  5],
       [ 5,  5,  5,  5],
       [-5,  5,  5,  5]])

In [13]:
result2=np.where(dataz>0,5,dataz)
result2

array([[-0.88341077, -0.31692026, -0.20435859,  5.        ],
       [ 5.        ,  5.        , -0.6709953 , -2.8732523 ],
       [ 5.        , -1.26263506,  5.        ,  5.        ],
       [-1.59270947,  5.        ,  5.        , -2.0839829 ],
       [-0.38393477,  5.        ,  5.        ,  5.        ],
       [ 5.        ,  5.        , -0.06159884, -1.15060275],
       [ 5.        , -0.43272997,  5.        ,  5.        ],
       [-0.1520418 ,  5.        ,  5.        ,  5.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [-0.72744689,  5.        ,  5.        ,  5.        ]])