<a href="https://colab.research.google.com/github/Shubhayang6/Numpy-basics/blob/main/index%20and%20slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
array1=np.array(np.arange(20))
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
array1[2 ]

2

In [5]:
array1[10:15]

array([10, 11, 12, 13, 14])

In [6]:
array1[10:15]=14
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 14, 14, 14, 14, 14, 15, 16,
       17, 18, 19])

In [7]:
array2=array1[10:15]
array2

array([14, 14, 14, 14, 14])

In [8]:
array2[2]=30

In [9]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 14, 14, 30, 14, 14, 15, 16,
       17, 18, 19])

In [11]:
array2[:]=50
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 50, 50, 50, 50, 50, 15, 16,
       17, 18, 19])

In [13]:
array2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
array2d[1]

array([4, 5, 6])

In [15]:
array2d[1][2]

6

In [16]:
array2d[1,2]

6

In [17]:
array3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
array3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
firstarray=array3d[0].copy()
firstarray

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
array3d[0]=60
array3d

array([[[60, 60, 60],
        [60, 60, 60]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
array3d[0]=firstarray
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
array3d[0,1]

array([4, 5, 6])

In [26]:
first_a=array3d[0]
first_a[1]

array([4, 5, 6])

In [27]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
array2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
array2d[:2,1]

array([2, 5])

In [32]:
array2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [33]:
array2d[1,:2]

array([4, 5])