In [2]:
import numpy

In [3]:
numpy.array([1,2,3])

array([1, 2, 3])

In [5]:
from numpy import *

In [6]:
array([1,2,3])

array([1, 2, 3])

In [7]:
import numpy as np


In [8]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
np.__version__

'1.19.5'

In [ ]:
array1=np.arange(100000)

In [ ]:
array2=list(range(100000))

In [16]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> fro
No Python documentation found for 'fro'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.

help> for
The "for" statement
*******************

The "for" statement is used to iterate over the elements of a sequence
(such as a string, tuple or list) or other iterable object:

   for_stmt ::=

In [17]:
help(np.sort
     )

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [18]:
from numpy import doc

In [19]:
help(doc
     )

Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    
    The following topics are available:
    
    - basics
    - broadcasting
    - byteswapping
    - constants
    - creation
    - dispatch
    - glossary
    - indexing
    - internals
    - misc
    - structured_arrays
    - subclassing
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    basics
    broadcasting
    byteswapping
    constants
    creation
    dispatch
    glossary
    indexing
    internals
    misc
    structured_arrays
    subclassing
    ufuncs

DATA
    __all__ = ['basics', 'broadcasting', 'byteswapping', 'constants', 'cre...

FILE
    /usr/local/lib/python3.7/dist-packages/numpy/doc/__init__.py




In [20]:
np.lookfor('arange')

Search results for 'arange'
---------------------------
numpy.arange
    Return evenly spaced values within a given interval.
numpy.ma.arange
    Return evenly spaced values within a given interval.
numpy.add
    Add arguments element-wise.
numpy.cov
    Estimate a covariance matrix, given data and weights.
numpy.dot
    Dot product of two arrays. Specifically,
numpy.gcd
    Returns the greatest common divisor of ``|x1|`` and ``|x2|``
numpy.ix_
    Construct an open mesh from multiple sequences.
numpy.lcm
    Returns the lowest common multiple of ``|x1|`` and ``|x2|``
numpy.mod
    Return element-wise remainder of division.
numpy.pad
    Pad an array.
numpy.put
    Replaces specified elements of an array with given values.
numpy.who
    Print the NumPy arrays in the given dictionary.
numpy.amax
    Return the maximum of an array or maximum along an axis.
numpy.amin
    Return the minimum of an array or minimum along an axis.
numpy.clip
    Clip (limit) the values in an array.
numpy.dia