<a href="https://colab.research.google.com/github/Shubhayang6/Numpy-basics/blob/main/Random%20number%20generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [12]:
samples1=np.random.randn(5)
samples1

array([-1.93113182, -0.64979542, -2.20753766,  0.06800825, -0.14546518])

In [13]:
np.random.randn()

0.2559603159727455

In [14]:
samples2=np.random.randn(2,3)
samples2

array([[ 0.59214699, -0.48223447,  0.80040839],
       [-1.03285654, -0.71268525,  0.91707426]])

In [15]:
np.random.randn(2,3,2)

array([[[-0.85918132, -0.32840501],
        [ 0.24685331,  0.67939535],
        [-0.87026555,  0.01518809]],

       [[ 1.04508042, -1.4003014 ],
        [ 0.01400309, -1.10321186],
        [-0.08545611,  2.44528467]]])

In [17]:
samples3=np.random.normal(size=(4,4))
samples3


array([[ 0.0736128 ,  1.07339208, -1.35273367, -1.68929595],
       [-0.27187404, -1.22298701,  1.28466577, -0.12288268],
       [-1.6307453 , -0.00904141, -0.02904719,  2.91549611],
       [-0.74517038,  0.04224524,  0.02653035,  0.76929112]])

In [18]:
from numpy.random import *

In [19]:
seed(1234)

In [20]:
x=randn(10)
x

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [21]:
y=randn(10)
y

array([ 1.15003572,  0.99194602,  0.95332413, -2.02125482, -0.33407737,
        0.00211836,  0.40545341,  0.28909194,  1.32115819, -1.54690555])

In [26]:
z=randint(10,20)
z

10

In [28]:
zs=randint(10,30,size=(2,5),dtype='int64')
zs


array([[22, 15, 27, 15, 23],
       [26, 19, 18, 22, 16]])

In [29]:
randint(10,30)

22

In [30]:
randn(10).reshape(2,5)

array([[-0.59165988,  0.04315596, -1.89610087,  0.68386223, -1.00655134],
       [ 0.00769448,  1.23084078,  2.00074455, -0.6721939 ,  0.91388772]])

In [31]:
rand=RandomState(1234)

In [32]:
rand.rand(10)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [33]:
rand.randint(10)

8

In [34]:
rand.randn(10)

array([ 2.00254961,  0.01086208, -0.86924706,  1.4249841 ,  0.1458091 ,
        2.89409095, -0.30426018,  0.861661  , -0.68992667,  0.18749737])

In [39]:
rand.normal(10)

9.339558587946323

In [40]:
rand.uniform(10)

4.887112126365377