<a href="https://colab.research.google.com/github/Shubhayang6/Numpy-basics/blob/main/sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

In [18]:
data=np.random.randn(10)
data

array([ 0.2704495 ,  2.03321344,  1.82961423, -0.06733779,  0.41468191,
        1.26313906, -0.68907585, -0.97840634, -0.45525959,  1.48867808])

In [20]:
data.sort()
data

array([-0.97840634, -0.68907585, -0.45525959, -0.06733779,  0.2704495 ,
        0.41468191,  1.26313906,  1.48867808,  1.82961423,  2.03321344])

In [22]:
data2=np.random.randn(10)
data2

array([ 0.38585482,  3.18301271,  0.26306423, -0.75835083,  0.18251893,
        0.48904388,  1.64227274,  1.4312589 , -0.83816174,  1.79302254])

In [23]:
np.sort(data2)

array([-0.83816174, -0.75835083,  0.18251893,  0.26306423,  0.38585482,
        0.48904388,  1.4312589 ,  1.64227274,  1.79302254,  3.18301271])

In [27]:
matrixdata=np.random.randn(6,3)
matrixdata

array([[ 0.01054238,  0.77839109,  0.56280464],
       [-0.32007952, -0.45706679, -0.57991907],
       [ 2.23643288,  1.03428643,  0.69532285],
       [ 1.10714259, -0.11533767, -0.14257069],
       [ 0.01389971,  1.07685912,  0.47925383],
       [-1.2194481 , -1.33797794, -0.16262839]])

In [33]:
matrixdata.sort(axis=-1)
matrixdata

array([[ 0.01054238,  0.56280464,  0.77839109],
       [-0.57991907, -0.45706679, -0.32007952],
       [ 0.69532285,  1.03428643,  2.23643288],
       [-0.14257069, -0.11533767,  1.10714259],
       [ 0.01389971,  0.47925383,  1.07685912],
       [-1.33797794, -1.2194481 , -0.16262839]])

In [35]:
matrixdata.sort(axis=0)
matrixdata

array([[-1.33797794, -1.2194481 , -0.32007952],
       [-0.57991907, -0.45706679, -0.16262839],
       [-0.14257069, -0.11533767,  0.77839109],
       [ 0.01054238,  0.47925383,  1.07685912],
       [ 0.01389971,  0.56280464,  1.10714259],
       [ 0.69532285,  1.03428643,  2.23643288]])