<a href="https://colab.research.google.com/github/Shubhayang6/Numpy-basics/blob/main/statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
data=np.random.randn(6,3)
data

array([[ 0.4334232 , -1.0487074 , -1.15526719],
       [ 0.56414443,  0.19224872,  0.3313954 ],
       [-0.460522  ,  2.21075465,  0.84241964],
       [ 0.05745992,  1.36633691, -0.48589478],
       [-0.12128874, -0.67341303,  0.08950018],
       [ 0.10712733, -0.51850888,  0.35068092]])

In [5]:
data.mean()

0.11566051528125526

In [6]:
data.min()

-1.1552671878087177

In [7]:
data.max()

2.210754647895809

In [8]:
data.sum()

2.081889275062595

In [10]:
data.sum(axis=0)

array([ 0.58034414,  1.52871096, -0.02716582])

In [12]:
data[:,0:1].sum()

0.5803441350192665

In [13]:
data.sum(axis=1)

array([-1.77055138,  1.08778854,  2.59265229,  0.93790205, -0.70520159,
       -0.06070063])

In [15]:
values=np.arange(5)

In [16]:
values.cumsum()
values

array([0, 1, 2, 3, 4])

In [18]:
values.std()

1.4142135623730951