<a href="https://colab.research.google.com/github/Shubhayang6/Numpy-basics/blob/main/universal%20functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data=np.arange(5)
data

array([0, 1, 2, 3, 4])

In [3]:
np.sqrt(data)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [4]:
np.exp(data)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [5]:
np.max(data)

4

In [6]:
np.min(data)

0

In [7]:
data1=np.random.randn(5)
data1

array([-0.78700289, -1.28901174,  0.38691478,  0.69473059,  0.25822723])

In [8]:
data2=np.random.randn(5)
data2

array([ 0.41206217, -0.58236373,  1.41501211, -0.30891091, -1.32981741])

In [10]:
np.maximum(data1,data2)

array([ 0.41206217, -0.58236373,  1.41501211,  0.69473059,  0.25822723])

In [12]:
data3=np.random.randn(10)*5
data3

array([-4.27156203,  7.67390421,  2.6802292 , -3.83418983, -2.19535389,
       -3.68265491, -1.34593295,  1.58311385, -3.68192887, -0.82872918])

In [14]:
fraction,integral=np.modf(data3)

In [15]:
integral

array([-4.,  7.,  2., -3., -2., -3., -1.,  1., -3., -0.])

In [16]:
fraction

array([-0.27156203,  0.67390421,  0.6802292 , -0.83418983, -0.19535389,
       -0.68265491, -0.34593295,  0.58311385, -0.68192887, -0.82872918])

In [17]:
np.abs(data3)

array([4.27156203, 7.67390421, 2.6802292 , 3.83418983, 2.19535389,
       3.68265491, 1.34593295, 1.58311385, 3.68192887, 0.82872918])

In [18]:
np.sqrt(np.abs(data3))

array([2.06677576, 2.77018126, 1.63714056, 1.95810874, 1.48167267,
       1.91902447, 1.1601435 , 1.25821852, 1.91883529, 0.91034564])

In [19]:
np.square(data3)

array([18.24624215, 58.88880576,  7.18362855, 14.70101162,  4.8195787 ,
       13.56194717,  1.8115355 ,  2.50624946, 13.55660021,  0.68679206])

In [20]:
np.rint(data3)

array([-4.,  8.,  3., -4., -2., -4., -1.,  2., -4., -1.])

In [23]:
data3

array([-4.27156203,  7.67390421,  2.6802292 , -3.83418983, -2.19535389,
       -3.68265491, -1.34593295,  1.58311385, -3.68192887, -0.82872918])

In [21]:
np.ceil(data3)

array([-4.,  8.,  3., -3., -2., -3., -1.,  2., -3., -0.])

In [26]:
data4=np.arange(10).reshape(2,5)
data4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
data5=np.arange(5,15).reshape(2,5)
data5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
np.add(data4,data5)

array([[ 5,  7,  9, 11, 13],
       [15, 17, 19, 21, 23]])

In [30]:
np.subtract(data4,data5)

array([[-5, -5, -5, -5, -5],
       [-5, -5, -5, -5, -5]])

In [31]:
np.multiply(data4,data5)

array([[  0,   6,  14,  24,  36],
       [ 50,  66,  84, 104, 126]])

In [32]:
np.divide(data4,data5)

array([[0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444],
       [0.5       , 0.54545455, 0.58333333, 0.61538462, 0.64285714]])

In [33]:
np.power(data4,data5)

array([[             0,              1,            128,           6561,
                262144],
       [       9765625,      362797056,    13841287201,   549755813888,
        22876792454961]])

In [34]:
np.greater(data4,data5)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [37]:
np.greater(data5,data4)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])